@URL = http://localhost:3000

###

# @name criarPessoa
POST {{URL}}/pessoa HTTP/1.1
content-type: application/json

{
    "nome": "Cicrano de Tal",
    "cpf": "22222222222",
    "dataNascimento": "1982-08-28"
}

###

# @name atualizarPessoa
PUT {{URL}}/pessoa/80 HTTP/1.1
content-type: application/json

{
    "nome": "Cicrano de Tal",
    "cpf": "22222222222",
    "dataNascimento": "1982-18-28"
}

###

# @name obterPessoa
GET {{URL}}/pessoa/1 HTTP/1.1

###

# @name excluirPessoa
DELETE  {{URL}}/pessoa/2 HTTP/1.1

###

# @name criarConta
POST {{URL}}/conta HTTP/1.1
content-type: application/json

{
    "idPessoa": "1",
    "limiteSaqueDiario": "1000",
    "flagAtivo": false,
    "tipoConta": "10",
    "dataCriacao": "2021-08-28"
}

###

# @name atualizarConta
PUT {{URL}}/conta/1 HTTP/1.1
content-type: application/json

{
    "idPessoa": "9",
    "limiteSaqueDiario": "200.00",
    "flagAtivo": true,
    "tipoConta": "2",
    "dataCriacao": "2021-08-28"
}

###

# @name obterConta
GET {{URL}}/conta/1 HTTP/1.1

###

# @name excluirConta
DELETE  {{URL}}/conta/3 HTTP/1.1

###

# @name obterSaldoConta
GET {{URL}}/conta/1/saldo HTTP/1.1

###

# @name depositarConta
PUT {{URL}}/conta/2/depositar HTTP/1.1
content-type: application/json

{
    "valor": 1000
}

###

# @name sacarConta
PUT {{URL}}/conta/2/sacar HTTP/1.1
content-type: application/json

{
    "valor": -30
}

###

# @name ativarDesativarConta
PUT {{URL}}/conta/2/ativar-desativar HTTP/1.1
content-type: application/json

{
    "ativo": true
}

###

# @name obterExtratoCompleto
GET {{URL}}/extrato/1 HTTP/1.1

###

# @name obterExtratoPeríodo
GET {{URL}}/extrato/1 HTTP/1.1
content-type: application/json

{
    "de": "2021-10-01",
    "ate": "2021-10-07"
}
